local wezterm = require("wezterm")
local nerdfonts = wezterm.nerdfonts
local constants = {}

constants.process_icons = {
    ["ansible"] = nerdfonts.dev_ansible,             -- Ansible automation
    ["aws"] = nerdfonts.dev_aws,                     -- AWS CLI
    ["awk"] = nerdfonts.md_code_array,              -- AWK text processing
    ["bash"] = nerdfonts.cod_terminal_bash,          -- Bash shell
    ["btm"] = nerdfonts.md_chart_donut_variant,     -- Bottom system monitor
    ["cargo"] = nerdfonts.dev_rust,                  -- Cargo (Rust package manager)
    ["cd"] = nerdfonts.md_folder_move,              -- Changing directory
    ["clang"] = nerdfonts.seti_c,                    -- Clang (C/C++ compiler)
    ["cmake"] = nerdfonts.seti_cmake,                -- CMake build tool
    ["cp"] = nerdfonts.md_file_copy,                -- Copying files
    ["curl"] = nerdfonts.md_web,                    -- Curl for web requests
    ["deno"] = nerdfonts.dev_deno,                   -- Deno runtime for JavaScript/TypeScript
    ["docker"] = nerdfonts.linux_docker,             -- Docker
    ["docker-compose"] = nerdfonts.linux_docker,     -- Docker Compose
    ["elixir"] = nerdfonts.dev_elixir,               -- Elixir language
    ["erlang"] = nerdfonts.custom_erlang,            -- Erlang language
    ["fastfetch"] = nerdfonts.md_speedometer,       -- Fastfetch system info
    ["fd"] = nerdfonts.dev_terminal,                 -- FD alternative for find
    ["find"] = nerdfonts.md_magnify,                -- Find command
    ["gcc"] = nerdfonts.seti_c,                      -- GCC (C compiler)
    ["gcloud"] = nerdfonts.dev_google_cloud_platform, -- GCP CLI
    ["gh"] = nerdfonts.dev_github_badge,             -- GitHub CLI
    ["git"] = nerdfonts.dev_git,                     -- Git version control
    ["go"] = nerdfonts.seti_go,                      -- Go programming language
    ["grep"] = nerdfonts.md_search_web,             -- Grep command
    ["helm"] = nerdfonts.md_helm,                   -- Helm package manager
    ["htop"] = nerdfonts.md_chart_bar,              -- Htop process manager
    ["ip"] = nerdfonts.md_network,                  -- IP command
    ["java"] = nerdfonts.dev_java,                   -- Java language
    ["javac"] = nerdfonts.dev_java,                  -- Java compiler
    ["k9s"] = nerdfonts.md_kubernetes,              -- Kubernetes dashboard
    ["kubectl"] = nerdfonts.md_kubernetes,          -- Kubernetes CLI
    ["ls"] = nerdfonts.md_folder,                   -- Listing files
    ["lua"] = nerdfonts.seti_lua,                    -- Lua programming language
    ["make"] = nerdfonts.seti_makefile,              -- Make build tool
    ["mongo"] = nerdfonts.dev_mongodb,               -- MongoDB database
    ["mv"] = nerdfonts.md_file_move,                -- Moving files
    ["mysql"] = nerdfonts.dev_mysql,                 -- MySQL database
    ["netstat"] = nerdfonts.md_chart_line,          -- Network statistics
    ["node"] = nerdfonts.dev_nodejs_small,           -- Node.js runtime
    ["nvim"] = nerdfonts.custom_vim,                 -- Neovim editor
    ["nu"] = nerdfonts.oct_command_palette,       -- Nushell
    ["packer"] = nerdfonts.md_package,              -- Packer
    ["perl"] = nerdfonts.custom_perl,                -- Perl language
    ["php"] = nerdfonts.dev_php,                     -- PHP language
    ["pip"] = nerdfonts.dev_python,                  -- Python package manager
    ["psql"] = nerdfonts.dev_postgresql,             -- PostgreSQL database
    ["python"] = nerdfonts.dev_python,               -- Python language
    ["rails"] = nerdfonts.dev_ruby_on_rails,         -- Ruby on Rails
    ["redis"] = nerdfonts.dev_redis,                 -- Redis database
    ["rm"] = nerdfonts.md_delete,                   -- Removing files
    ["ruby"] = nerdfonts.dev_ruby,                   -- Ruby language
    ["rust"] = nerdfonts.dev_rust,                   -- Rust programming language
    ["scala"] = nerdfonts.dev_scala,                 -- Scala language
    ["sed"] = nerdfonts.md_text_box,                -- Sed text stream editor
    ["sudo"] = nerdfonts.fa_hashtag,                 -- Sudo command
    ["terraform"] = nerdfonts.dev_terraform,         -- Terraform
    ["tmux"] = nerdfonts.dev_terminal,               -- Tmux terminal multiplexer
    ["top"] = nerdfonts.md_chart_bar,               -- Top process manager
    ["traceroute"] = nerdfonts.md_router,           -- Traceroute
    ["tsc"] = nerdfonts.dev_typescript,              -- TypeScript compiler
    ["typescript"] = nerdfonts.dev_typescript,       -- TypeScript language
    ["vagrant"] = nerdfonts.dev_vagrant,             -- Vagrant
    ["vim"] = nerdfonts.dev_vim,                     -- Vim editor
    ["wget"] = nerdfonts.md_download,               -- Wget for file downloads
    ["yazi"] = nerdfonts.dev_terminal,               -- Yazi file explorer
    ["zsh"] = nerdfonts.dev_terminal,                -- Zsh shell
}

return constants