[common.files]
"shared/linters" = "~/.config"
"shared/cargo" = "~/.cargo"
"shared/fastfetch" = "~/.config/fastfetch"
"shared/mise" = "~/.config/mise"
"shared/nvim" = "~/.config/nvim"
"shared/starship" = "~/.config"

[windows.files]
"windows/ahk" = "C:\\Users\\2015m\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"
"windows/komorebi" = "~/.config/komorebi"
"windows/nushell" = "~/.config/nushell"
"windows/wezterm" = "~/.config/wezterm"

[mac.files]
"unix/bash" = "~/.config/bash"
"unix/zsh" = "~/.config/zsh"
"unix/borders" = "~/.config/borders"
"unix/aerospace" = "~/.config/aerospace"
"unix/bottom" = "~/Library/Application Support/bottom"
"unix/ghostty" = "~/.config/ghostty"
"unix/zellij" = "~/.config/zellij"
"unix/sketchybar" = "~/.config/sketchybar"
