[common.files]
"common/linters" = "~/.config"
"common/cargo" = "~/.cargo"
"common/fastfetch" = "~/.config/fastfetch"
"common/mise" = "~/.config/mise"
"common/nvim" = "~/.config/nvim"
"common/starship" = "~/.config"
"common/zsh" = "~/.config/zsh"
"common/bash" = "~/.config/bash"
"common/zellij" = "~/.config/zellij"

[windows.files]
"windows/ahk" = "C:\\Users\\2015m\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"
"windows/komorebi" = "~/.config/komorebi"
"windows/nushell" = "~/.config/nushell"
"windows/wezterm" = "~/.config/wezterm"
"windows/wsl/.wslconfig" = "~/.wslconfig"

[mac.files]
"common/bottom" = "~/Library/Application Support/bottom"
"macos/borders" = "~/.config/borders"
"macos/aerospace" = "~/.config/aerospace"
"macos/ghostty" = "~/.config/ghostty"

[linux.files]
"common/bottom" = "~/.config/bottom"
"windows/wsl/.hushlogin" = "~/.hushlogin"
